### ISSUE TITLE
When span.kind() is null, It occurs null exception.

### ISSUE THREAD

**Issue by hamelmoon** [ExpediaDotCom/spring-cloud-sleuth-haystack-reporter#3]
When span.kind() is null, It occurs null exception.
Please, Check this.

https://github.com/ExpediaDotCom/spring-cloud-sleuth-haystack-reporter/blob/a4446e630e717d6d1c6bfc145cfbf97e2f0c6bcc/src/main/java/com/expedia/www/spring/cloud/sleuth/haystack/reporter/reporters/HaystackReporter.java#L75

**Comment by doctorXWrites** [comment]
#7 The PR removes the code block itself for adding the log Tags since it was found its been already done in the haystack reader. @hamelmoon thanks for pointing this out.

**Comment by doctorXWrites** [comment]
@hamelmoon we are going to release this on Monday. Please do report if you find anything else is a miss.

**Comment by hamelmoon** [comment]
OK, let me know when the haystack reader was deployed!

**Comment by doctorXWrites** [comment]
Sorry, i think i didn't get your question. Are you asking us to test this after deploying with haystack reader, we already did that.

**Comment by doctorXWrites** [comment]
Closing this issue as of now. Released in Version 1.0

**Comment by hamelmoon** [comment]
haha, I thought that you fixed code in another Repo.  I tested the null case. It works well.

**Comment by doctorXWrites** [comment]
:)
Thank you for contributing.
